/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author User
 */
public class CentralMain extends javax.swing.JFrame {

    /**
     * Creates new form CentralMain
     */
    public CentralMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btndelivery = new rojerusan.RSMaterialButtonRectangle();
        btnrelief = new rojerusan.RSMaterialButtonRectangle();
        btnback = new rojerusan.RSMaterialButtonRectangle();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MAIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 140, 80));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SECTION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 510));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndelivery.setBackground(new java.awt.Color(0, 181, 204));
        btndelivery.setText("Delivery Section");
        btndelivery.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        btndelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeliveryActionPerformed(evt);
            }
        });
        jPanel2.add(btndelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 230, 60));

        btnrelief.setBackground(new java.awt.Color(0, 181, 204));
        btnrelief.setText("Relief Section");
        btnrelief.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        btnrelief.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreliefActionPerformed(evt);
            }
        });
        jPanel2.add(btnrelief, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 230, 60));

        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel2.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 100, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 380, 510));

        setSize(new java.awt.Dimension(676, 506));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(this, "Would you like to log out?","",JOptionPane.YES_NO_OPTION);
        if(n==0){
        welcome wel = new welcome();
        wel.setVisible(true);
        wel.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        wel.setResizable(false);
        dispose();  
        }
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnreliefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreliefActionPerformed
        // TODO add your handling code here:
        Releif rel = new Releif();
        rel.A1.setText("60");
        rel.A2.setText("50");
        rel.A3.setText("70");
        
        rel.A1.setEditable(false);
        rel.A2.setEditable(false);
        rel.A3.setEditable(false);
        
        FileReader fr = null;
        
        try {
            fr = new FileReader("left.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CentralMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        BufferedReader br = new BufferedReader(fr);
        
        String str;
        
        ArrayList<String> arr = new ArrayList<String>();
        
        try {
            while((str = br.readLine())!=null)
            {
                arr.add(str);
            }
        } catch (IOException ex) {
            Logger.getLogger(CentralMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(CentralMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        rel.L1.setText(arr[0]);
//        rel.L2.setText(arr[1]);
//        rel.L3.setText(arr[2]);

        rel.T.setText(arr.get(0));
        rel.L1.setText(arr.get(1));
        rel.L2.setText(arr.get(2));
        rel.L3.setText(arr.get(3));
        
        rel.T.setEditable(false);
        rel.L1.setEditable(false);
        rel.L2.setEditable(false);
        rel.L3.setEditable(false);

        rel.setVisible(true);
        rel.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        rel.setResizable(false);
        dispose();
    }//GEN-LAST:event_btnreliefActionPerformed

    private void btndeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeliveryActionPerformed
        // TODO add your handling code here:
        SendReleif send = new SendReleif();
        send.setVisible(true);
        send.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        send.setResizable(false);
        dispose();
                
    }//GEN-LAST:event_btndeliveryActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CentralMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CentralMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CentralMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CentralMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CentralMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnback;
    private rojerusan.RSMaterialButtonRectangle btndelivery;
    private rojerusan.RSMaterialButtonRectangle btnrelief;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
